# This is a complete example of a config.toml file for Porla. The values shown are the default values which are
# included in the release config.

[session]
base = "default"
presets = [
    "presets/01-set-utp-params.toml"
]

[sqlite]
# the sqlite file to use. set to :memory: to use an in-memory database.
file = "porla.sqlite"
