FROM alpine:3.18.0 AS build-env
WORKDIR /src
COPY . .
ENV VCPKG_FORCE_SYSTEM_BINARIES="1"
RUN apk add --update --no-cache cmake curl g++ git libc6-compat linux-headers make perl pkgconfig python3 unzip zip bash \
    && bash builder-env.sh
