FROM debian:12.1-slim AS build-env

WORKDIR /src

COPY . .

ENV VCPKG_FORCE_SYSTEM_BINARIES="1"

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y cmake curl g++ git make perl pkg-config python3 unzip wget zip \
    && bash builder-env.sh
