/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexLayoutImport } from './routes/_auth/_indexLayout'
import { Route as AuthIndexLayoutTabLayoutImport } from './routes/_auth/_indexLayout/_tabLayout'
import { Route as AuthIndexLayoutTabLayoutIndexImport } from './routes/_auth/_indexLayout/_tabLayout/index'
import { Route as AuthIndexLayoutTabLayoutTrackerImport } from './routes/_auth/_indexLayout/_tabLayout/tracker'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexLayoutRoute = AuthIndexLayoutImport.update({
  id: '/_indexLayout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthIndexLayoutTabLayoutRoute = AuthIndexLayoutTabLayoutImport.update({
  id: '/_tabLayout',
  getParentRoute: () => AuthIndexLayoutRoute,
} as any)

const AuthIndexLayoutTabLayoutIndexRoute =
  AuthIndexLayoutTabLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AuthIndexLayoutTabLayoutRoute,
  } as any)

const AuthIndexLayoutTabLayoutTrackerRoute =
  AuthIndexLayoutTabLayoutTrackerImport.update({
    path: '/tracker',
    getParentRoute: () => AuthIndexLayoutTabLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_indexLayout': {
      preLoaderRoute: typeof AuthIndexLayoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_indexLayout/_tabLayout': {
      preLoaderRoute: typeof AuthIndexLayoutTabLayoutImport
      parentRoute: typeof AuthIndexLayoutImport
    }
    '/_auth/_indexLayout/_tabLayout/tracker': {
      preLoaderRoute: typeof AuthIndexLayoutTabLayoutTrackerImport
      parentRoute: typeof AuthIndexLayoutTabLayoutImport
    }
    '/_auth/_indexLayout/_tabLayout/': {
      preLoaderRoute: typeof AuthIndexLayoutTabLayoutIndexImport
      parentRoute: typeof AuthIndexLayoutTabLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthIndexLayoutRoute.addChildren([
      AuthIndexLayoutTabLayoutRoute.addChildren([
        AuthIndexLayoutTabLayoutTrackerRoute,
        AuthIndexLayoutTabLayoutIndexRoute,
      ]),
    ]),
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
