name: Version

on:
  workflow_call:
    inputs:
      ref:
        description: 'Ref or SHA to calculate the version for'
        type: string
        default: ''
    outputs:
      fullSemVer:
        value: ${{ jobs.gitversion.outputs.fullSemVer }}
      majorMinorPatch:
        value: ${{ jobs.gitversion.outputs.majorMinorPatch }}
      shortSha:
        value: ${{ jobs.gitversion.outputs.shortSha }}
      major:
        value: ${{ jobs.gitversion.outputs.major }}
      minor:
        value: ${{ jobs.gitversion.outputs.minor }}
      patch:
        value: ${{ jobs.gitversion.outputs.patch }}

jobs:
  gitversion:
    name: Run GitVersion
    runs-on: ubuntu-latest
    outputs:
      fullSemVer:      ${{ steps.gitversion.outputs.fullSemVer }}
      majorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
      shortSha:        ${{ steps.gitversion.outputs.shortSha }}
      major:           ${{ steps.gitversion.outputs.major }}
      minor:           ${{ steps.gitversion.outputs.minor }}
      patch:           ${{ steps.gitversion.outputs.patch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.8.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.7.0
